[[redirect]]
  from = "/udacity/nano-degrees/full-stack-js"
  to = "/udacity/full-stack-nano-degree"
  status = 301
[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.22.10"
  YARN_FLAGS = "--no-ignore-optional"